version: '3'
services:
    database:
        build: 
          context: ./dockerfileBBDD
          dockerfile: Dockerfile
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_DATABASE: panaur
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./:/docker-entrypoint-initdb.d
        networks:
            - default
    web:
        build: 
          context: ./dockerfileWWW
          dockerfile: Dockerfile
        ports: 
            - 80:80 
        volumes:
            - ./:/var/www/html
        links:
            - database
        networks:
            - default
    phpmyadmin:
        build: 
          context: ./dockerfilePHP
          dockerfile: Dockerfile
        links: 
            - database
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
